from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER


class PDFService:

    def generate_report(
        self,
        output_path,
        report_data,
    ):

        styles = getSampleStyleSheet()

        title_style = styles["Heading1"]
        title_style.alignment = TA_CENTER

        heading = styles["Heading2"]
        normal = styles["BodyText"]

        pdf = SimpleDocTemplate(output_path)

        elements = []

        # -----------------------
        # Title
        # -----------------------

        elements.append(
            Paragraph(
                "InsightIQ AI Data Analysis Report",
                title_style,
            )
        )

        elements.append(Spacer(1, 20))

        # -----------------------
        # Dataset Summary
        # -----------------------

        elements.append(
            Paragraph(
                "Dataset Summary",
                heading,
            )
        )

        summary = report_data["dataset_summary"]

        elements.append(
            Paragraph(
                f"<b>Dataset:</b> {summary['dataset_name']}",
                normal,
            )
        )

        elements.append(
            Paragraph(
                f"<b>Rows:</b> {summary['rows']}",
                normal,
            )
        )

        elements.append(
            Paragraph(
                f"<b>Columns:</b> {summary['columns']}",
                normal,
            )
        )

        elements.append(
            Paragraph(
                f"<b>Target Column:</b> {summary['target_column']}",
                normal,
            )
        )

        elements.append(
            Paragraph(
                f"<b>Problem Type:</b> {summary['problem_type']}",
                normal,
            )
        )

        elements.append(Spacer(1, 20))

        # -----------------------
        # Data Quality
        # -----------------------

        elements.append(
            Paragraph(
                "Data Quality",
                heading,
            )
        )

        quality = report_data["data_quality"]

        elements.append(
            Paragraph(
                f"<b>Missing Values:</b> {quality['missing_values']}",
                normal,
            )
        )

        elements.append(
            Paragraph(
                f"<b>Duplicate Rows:</b> {quality['duplicates']}",
                normal,
            )
        )

        elements.append(
            Paragraph(
                f"<b>Outliers:</b> {len(quality['outliers'])}",
                normal,
            )
        )

        elements.append(Spacer(1, 20))

        # -----------------------
        # AutoML
        # -----------------------

        elements.append(
            Paragraph(
                "AutoML Result",
                heading,
            )
        )

        elements.append(
            Paragraph(
                f"<b>Best Model:</b> {report_data['best_model']}",
                normal,
            )
        )

        elements.append(Spacer(1, 20))

        # -----------------------
        # AI Explanation
        # -----------------------

        elements.append(
            Paragraph(
                "AI Explanation",
                heading,
            )
        )

        for line in report_data["explanation"]:
            elements.append(
                Paragraph(line, normal)
            )

        elements.append(Spacer(1, 20))

        # -----------------------
        # Suggestions
        # -----------------------

        elements.append(
            Paragraph(
                "Recommendations",
                heading,
            )
        )

        for suggestion in report_data["suggestions"]:
            elements.append(
                Paragraph(
                    "• " + suggestion,
                    normal,
                )
            )

        elements.append(Spacer(1, 30))

        elements.append(
            Paragraph(
                "<b>Generated by InsightIQ</b>",
                normal,
            )
        )

        pdf.build(elements)